services:
  - type: web
    name: stock-pulse-predictor
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
    plan: free
