services:
  - type: web
    name: stockpulse-predictor
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000
