version: "1"
services:
  - type: web
    name: stock-pulse-predictor-1
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
